### ISSUE TITLE
Scrapper error

### ISSUE THREAD

**Issue by aviaryan** [fossasia/open-event-scraper#15]
Some recent change in spreadsheet is causing errors in the scrapper.

```
INFO:root:[Parsing Track] 'Science Hack Day'
INFO:root:next...
INFO:root:[Fetching Track] 'Linux and MiniDebConf', gid = 1565143498
INFO:root:GET https://docs.google.com/spreadsheets/d/1QeAyxbEc1fP9h5_kGQh-EVrx5RaYgbKFJBE9wUjIdvc/ex
port?format=tsv&gid=1565143498
Traceback (most recent call last):
  File "scraper.py", line 253, in <module>
    data = fetch_tsv_data(track.gid)
  File "scraper.py", line 224, in fetch_tsv_data
    res = urllib2.urlopen(url)
  File "/app/.heroku/python/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/app/.heroku/python/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/app/.heroku/python/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/app/.heroku/python/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/app/.heroku/python/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/app/.heroku/python/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request
```

**Comment by aviaryan** [comment]
@mariobehling Can you please have a look at the [spreadsheet](https://docs.google.com/spreadsheets/d/1QeAyxbEc1fP9h5_kGQh-EVrx5RaYgbKFJBE9wUjIdvc/edit#gid=1565143498). GID of row 16 ( Linux and MiniDebConf ) doesn't exists.

**Comment by aviaryan** [comment]
It was fixed around 3 hours before.
Closing.
